---

# Fixes DNS resolution to contact public Red Hat servers from within OS1
- name: Configure DHCP client to ignore dynamic DNS configurations
  copy: src=ifcfg-eth0 dest=/etc/sysconfig/network-scripts/ifcfg-eth0 owner=root group=root
  notify:
     - Restart Network
     - Network Restarted
  tags:
     - network

- name: Configure custom DNS servers
  copy: src=resolv.conf dest=/etc/resolv.conf owner=root group=root
  notify:
     - Restart Network
     - Network Restarted
  tags:
     - network

- name: Tune mount point of root
  mount: name=/ src=/dev/vda1 fstype=ext4 opts=noatime,barrier=0 state=mounted

# We leave this on /mnt as default as it's hell to move (and default is ext3)
- name: Mount the ephemeral store drive as /mnt
  mount: name=/mnt src=/dev/vdb fstype=ext3 opts=noatime,barrier=0 state=mounted

# Add 8GB swap space!
# Important to use generous tmpfs sizes during builds

- name: Ensure we have some swap space
  shell: "dd if=/dev/zero of=/mnt/swapfile bs=1024 count=8388608 && mkswap /mnt/swapfile && swapon /mnt/swapfile"
  args:
    creates: /mnt/swapfile

- name: Make the swap file secure
  file: path=/mnt/swapfile state=file mode="0600" owner="root" group="root"

- name: Update fstab to use the swapfile on reboot
  mount: name=none
         src=/mnt/swapfile
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present

- name: "Disable password authentication"
  replace:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication yes"
    replace: "PasswordAuthentication no"
  notify:
    - Restart sshd
  tags:
    - password-auth
