---

- name: Add passwordless connection for jenkins
  copy: src=authorized_keys dest=/home/jenkins/.ssh/authorized_keys mode=0600 owner=jenkins

#Ensure Jenkins is NOT installed: the master auto-installs it!
- name: Ensure Jenkins is NOT installed
  yum: name=jenkins state=absent

# Create Jenkins work directory
- name: Create /var/lib/jenkins
  file: path=/var/lib/jenkins state=directory mode=0700 owner=jenkins

# Install Docker, provide scripts for starting/stopping CouchDB/MongoDB via Docker
- name: Install Docker
  yum: name=docker state=present

- name: Create docker_conf
  copy: src=docker_conf dest=/etc/sudoers.d/docker_conf mode=0440 owner=root

- name: Start Docker
  service: name=docker enabled=yes state=started

- name: create docker_run_mongodb.sh
  copy: src=docker_run_mongodb.sh dest=/usr/bin/docker_run_mongodb.sh mode=0700 owner=root

- name: create docker_stop_container.sh
  copy: src=docker_stop_container.sh dest=/usr/bin/docker_stop_container.sh mode=0700 owner=root

# Install CouchDB (Avoiding Docker because of issues)
- name: Get the the latest version of CouchDB
  yum: name=couchdb state=latest

- name: Start CouchDB
  service: name=couchdb enabled=yes state=started

# Install Cassandra (Avoiding Docker for now due to stability issues)
- name: Configure Datastax repo
  copy: src=datastax.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: Install Cassandra
  yum: name=dsc21 enablerepo=datastax state=latest

- name: Start Cassandra
  service: name=cassandra enabled=yes state=started

# Install packages required for web site build / Ruby environment
- name: Web site build tool chain (GCC, headers etc.)
  yum: name={{item}} state=present
  with_items:
   - gcc
   - make
   - ruby-devel
   - gcc-c++
   - libxml2-devel
   - libxslt-devel

# Gems required for web-site build
- name: Install Rake
  sudo: yes
  sudo_user: jenkins
  command: bash -lc "gem install rake"

- name: Install Bundler
  sudo: yes
  sudo_user: jenkins
  command: bash -lc "gem install bundler"
